name: Run Pytests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    if: (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != 'Kushallodha/cosmoprimo')
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Latest Python 3.12"
            os: ubuntu-latest
            python-version: "3.12"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true


    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "numpy<2.0.0"
        # Install the package in development mode
        pip install matplotlib pytest pytest-cov requests cobaya
        pip install -e .[class,camb,astropy,jax,extras]
        # Install test dependencies
        
    
    
    - name: Test with pytest
      run: |
        pytest cosmoprimo/tests/ -v --cov=cosmoprimo --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
